baseURL = 'https://guhebushiguhe.github.io/hugo-test'
title = 'My New Hugo Site'


languageCode = 'zh-CN'
defaultContentLanguage = 'zh-CN'
[languages]
[languages.zh-CN]
languageName = '简体中文'
weight = 1

theme = 'hugo-theme-reimu'